// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBII_uNGIQoKJtsL7CmfRMHyofy7vI58',
    appId: '1:118480418579:web:38c832d3cf1e7d5df10ce6',
    messagingSenderId: '118480418579',
    projectId: 'myfinanceapp-e9945',
    authDomain: 'myfinanceapp-e9945.firebaseapp.com',
    storageBucket: 'myfinanceapp-e9945.appspot.com',
    measurementId: 'G-74NXDS7C1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ1LrbrdaS3PxmEJJpV6tkHU7Ff8vyUqg',
    appId: '1:118480418579:android:d4bfff8cfab540dbf10ce6',
    messagingSenderId: '118480418579',
    projectId: 'myfinanceapp-e9945',
    storageBucket: 'myfinanceapp-e9945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMKa_yWp-R5C6k1tzPEe4dJMcpoM7fjM',
    appId: '1:118480418579:ios:a45705150bca1ea0f10ce6',
    messagingSenderId: '118480418579',
    projectId: 'myfinanceapp-e9945',
    storageBucket: 'myfinanceapp-e9945.appspot.com',
    iosBundleId: 'com.sliit.myfinanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkMKa_yWp-R5C6k1tzPEe4dJMcpoM7fjM',
    appId: '1:118480418579:ios:a45705150bca1ea0f10ce6',
    messagingSenderId: '118480418579',
    projectId: 'myfinanceapp-e9945',
    storageBucket: 'myfinanceapp-e9945.appspot.com',
    iosBundleId: 'com.sliit.myfinanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWBII_uNGIQoKJtsL7CmfRMHyofy7vI58',
    appId: '1:118480418579:web:3a2c88c3a5c2f78ff10ce6',
    messagingSenderId: '118480418579',
    projectId: 'myfinanceapp-e9945',
    authDomain: 'myfinanceapp-e9945.firebaseapp.com',
    storageBucket: 'myfinanceapp-e9945.appspot.com',
    measurementId: 'G-XRM4XPTFSY',
  );

}